### ISSUE TITLE
401 Bad creds with public_repo on Travis

### ISSUE THREAD

**Issue by fenollp** [japaric/trust#51]
I am probably doing something wrong somewhere...

I followed the instruction in .travis.yml to create the GH_TOKEN but my builds fail with 401:
https://travis-ci.org/fenollp/minrs/builds/191088904

Am I doing too many requests? Should I use `repo` instead of `public_repo`?

Thanks

**Comment by japaric** [comment]
Did you encrypt the token, literally, as "GH_TOKEN=0123456789012345678901234567890123456789"?

Because you have to encrypt it with the GH_TOKEN part, that is:

```
$ travis encrypt 0123456789012345678901234567890123456789
```

within the directory of the repository.

>  Should I use repo instead of public_repo?

It has to be public_repo.

**Comment by fenollp** [comment]
Yep, +1 for #52 !

**Comment by japaric** [comment]
Fixed in #52. Sorry for the trouble.
