### ISSUE TITLE
Install latest 0.1.x version of cross

### ISSUE THREAD

**Issue by japaric** [japaric/trust#56]
Right now the MAJJOR.MINOR.PATCH version of cross is hard coded in ci/install.sh. Let's change it so we always install the latest MAJOR.MINOR.* version instead; that way most users won't have to update that number so often. This is going to mainly involve teaching the [install.sh](https://github.com/japaric/trust/blob/gh-pages/install.sh) script to accept MAJOR.MINOR as a valid `--tag`.

**Comment by fenollp** [comment]
This can be closed.
