### ISSUE TITLE
More descriptive comment on build: false

### ISSUE THREAD

**Issue by faern** [japaric/trust#58]
This part of `appveyor.yml` is not easy to understand for someone not very familiar with Appveyor:

```yml
# disable automatic builds
build: false
```

It sounds like it turns off automatically building new commits to the project. Which it doesn't.

If the following comment is correct I would say it describes the setting in a clearer way:
```yml
# We build in the test stage, so disable Appveyor's build stage.
build: false
```

**Comment by Susurrus** [comment]
Can you submit a PR for this?

**Comment by faern** [comment]
Sure!
