### ISSUE TITLE
gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by manuels** [japaric/trust#68]
I just setup `trust`. However, I am running into a problem:

    +curl -LSfs https://japaric.github.io/trust/install.sh
    install.sh: GitHub repository: https://github.com/japaric/cross
    install.sh: Crate: cross
    install.sh: Tag: v0.1.10
    install.sh: Target: x86_64-unknown-linux-gnu
    install.sh: Installing to: /home/travis/.cargo/bin
    gzip: stdin: not in gzip format
    tar: Child returned status 1
    tar: Error is not recoverable: exiting now

Not sure why this happens. The complete log can be found here:
https://travis-ci.org/manuels/bulletinboard-dht/jobs/218182794

**Comment by japaric** [comment]
Ugh, the automated deploy of the latest releases (yesterday) failed. I have done a manual deploy, please try again (restart the job on the Travis dashboard)

**Comment by manuels** [comment]
Thanks for the quick response! I just queued a new job. Let's see what happens:
https://travis-ci.org/manuels/bulletinboard-dht/jobs/218182814

**Comment by manuels** [comment]
This error seems to be fixed! Thanks, @japaric!
(There is another error, but that's a problem with my crate)
