### ISSUE TITLE
Question: External libraries?

### ISSUE THREAD

**Issue by jD91mZM2** [japaric/trust#80]
Hey, so I wonder: Is it possible to use external libraries with this project? How?

Thanks! This project seems very cool, and I can't wait to finally be able to cross compile my project lol.

**Comment by RadicalZephyr** [comment]
Trust uses [cross](https://github.com/rust-embedded/cross) for actually doing most of the builds.  If you mean you need extra dependencies for building your project then you probably want to build a [custom docker image](https://github.com/rust-embedded/cross#custom-docker-images) based on the official cross images you need.

**Comment by jD91mZM2** [comment]
Thanks!
