### ISSUE TITLE
Compilation script suddenly stopped working

### ISSUE THREAD

**Issue by Limeth** [japaric/trust#90]
[This](https://travis-ci.org/Limeth/euclider/builds/230017640) is the first Travis build that started failing with the following error:

```
$ bash ci/install.sh
++dirname ci/install.sh
+. ci/utils.sh
+main
+install_c_toolchain
+case $TARGET in
+install_rustup
+sh /home/travis/rust/lib/rustlib/uninstall.sh
sh: 0: Can't open /home/travis/rust/lib/rustlib/uninstall.sh
The command "bash ci/install.sh" failed and exited with 127 during .
Your build has been stopped.
```

Any ideas what this could be caused by? I didn't edit any CI files in that commit.
Thank you in advance.

**Comment by japaric** [comment]
Your [install.sh](https://github.com/Limeth/euclider/blob/master/ci/install.sh) script doesn't look like [trust's](https://github.com/japaric/trust/blob/v0.1.0/ci/install.sh); it looks like [rust-everywhere's](https://github.com/japaric/rust-everywhere/blob/master/ci/install.sh) which predates trust existence and already has been deprecated.

I'd suggest starting from trust master branch. These days you don't need to manually install rustup as trust v0.1.1 did.

(That reminds me that I should make a new trust release)

**Comment by Limeth** [comment]
Sorry for the confusion, I changed the project to use trust and it seems to be working properly. Thank you.
